### ISSUE TITLE
no list of available BBSes

### ISSUE THREAD

**Issue by ch0mik** [sblendorio/petscii-bbs#18]
> $ java -jar petscii-bbs-1.0-SNAPSHOT.jar 
> usage: petscii-bbs-1.0-SNAPSHOT.jar
>  -b,--bbs <arg>       Run specific BBS (mandatory - see list below)
>  -h,--help            Displays help
>  -p,--port <arg>      TCP port used by server process (default 6510)
>  -t,--timeout <arg>   Socket timeout in millis (default 60 minutes)
> List of available BBS:

no list of available BBSes - what is wrong ?

PS. I build it via docker 
`docker run -it --rm -v "$(pwd)":/tmp/bbsjava/petscii-bbs -w /tmp/bbsjava/petscii-bbs maven mvn clean install package`

and then run it via 
`java -jar target/petscii-bbs-1.0-SNAPSHOT.jar`

log : https://pastebin.pl/view/4bcb467f

**Comment by sblendorio** [comment]
I will try to do the same ASAP. Meanwhile, what if you take the .jar from Docker and run it on local machine?

**Comment by ch0mik** [comment]
Yes, The Docker Container has maped local path to src from git. The target is too on my local path.
Next, I run jar from target `java -jar target/petscii-bbs-1.0-SNAPSHOT.jar`

**Comment by sblendorio** [comment]
Just replicated it. Which version of JRE are you using, running the jar file?

- If I use JRE 1.8, it works
- If I use JRE 11, it does NOT work. It seems to be an issue related to reflection mechanism.

Please try JRE 1.8 and let me know

**Comment by sblendorio** [comment]
Just made a commit 264e84edec71de434aece267d5a331ea5dbabbc8 that should have fixed your problem. Do try also to run jar file with Java 11+ and let me know.

Now minimum JDK required is 1.8 (instead of 1.7).

**Comment by ch0mik** [comment]
Hi!, it works ! ThX.
Regards
Pawel
