### ISSUE TITLE
Conversion of the Chatroom to allow Public chat

### ISSUE THREAD

**Issue by eightbitswide** [sblendorio/petscii-bbs#37]
Is there a way to convert the existing chatroom to allow for public messages?

It would appear that 

**sendToAll(new ChatMessage(-1, getClientName() + text));**

in the correct location would allow messages which did not conform to the other if statement to be posted publicly, but with **java** not being my primary programming language (python/perl programmer here) it is completely escaping me.

Thanks
Jeff

**Comment by eightbitswide** [comment]
For the moment, I've implemented ssshake's chatroom mods.  
https://github.com/ssshake/theoldnet-bbs
This issue can be closed.

**Comment by sblendorio** [comment]
Just updated Chat.java public to allow "public room" chat
