### ISSUE TITLE
80 column petscii bbs

### ISSUE THREAD

**Issue by jalbarracinv** [sblendorio/petscii-bbs#39]
Thank you for creating this code!

I want to build a bbs with 80 columns petscii chars. 

I believe I have to edit CLIScreenModel.java  and modify the numbers:
static int BUFFER_LENGTH = 880; // = 40 columns x 22 rows (+1 for title + 2 for input)

for example for the screen size 80 columns x 50 rows, I have to edit to:
static int BUFFER_LENGTH = 3760; // = 80 columns x 47 rows (+1 for title + 2 for input)

and also this lines (changing 40 to 80):
int rowCount = row.length() / 40;
newContent = row.substring(maxRows * 40) + "\n" + newContent;
int spaces = 40 - adventureName.length() - 1 - rightStatus.length();

and it should work?

**Comment by sblendorio** [comment]
So you're speaking about Zork Engine.

BBS code for Zork Engine is in the package `org.zmpp.textui.bbs`, not in `org.zmpp.textui.cli`.

So code to modify to support 80 columns BBS is:

- in class  **BBSScreenModel**, method **wordWrap**, change:
`                    .maxWidth(39)`
into:
`                    .maxWidth(79)`

- supposing **50 rows**, in class  **BBSScreenModel**, method **checkForScreenPaging**, change:
`        if (nlines >= 24) {`
into:
`        if (nlines >= 49) {`

Are you creating a BBS for Commander X16?

**Comment by jalbarracinv** [comment]
Yes for the Commander X16!! --> Do you know another projects about CX16?

**Comment by sblendorio** [comment]
Can Commander X16 connect to BBS?

Il ven 5 giu 2020, 15:57 jalbarracinv <notifications@github.com> ha scritto:

**Comment by jalbarracinv** [comment]
Via RS232 but right now no terminals available. Some day :)
