### ISSUE TITLE
bbs.retrocampus.com >> CHATGPT >> accents not displayed properly > a way to simplify it ?

### ISSUE THREAD

**Issue by mamatdunet** [sblendorio/petscii-bbs#59]
Hi,

What an amazing project that you've made, thank you ! I'm using this card : https://www.tindie.com/products/iodeo/minitel-esp32-dev-board/ 

On a Minitel and also on http://bbs.retrocampus.com/, the accents (in french like "é", "è", "à", "ù" for example, are not displayed well on chatGPT as you can see on screenshots.

<img width="677" alt="Capture d’écran 2023-08-21 à 17 39 17" src="https://github.com/sblendorio/petscii-bbs/assets/4966194/adea20c1-9735-4b22-aed8-23a48c8ebeaa">
<img width="1295" alt="Capture d’écran 2023-08-21 à 19 10 24" src="https://github.com/sblendorio/petscii-bbs/assets/4966194/3e6193c1-9c16-43f0-89fe-c40f5706ed66">

I'm not sure that the Minitel as ever been compatible with accents by the way. So I suggest to fix it, to replace each output with an accent by his equivalent without accent : 
à > a
â > a
é > e
è > e
ê > e
î > i
ï > i
ô > o
ù > u
û > u
ü > u
ç > c
œ > oe

Would you like to fix this or it's not your priority at all ? 😅

**Comment by mamatdunet** [comment]
Cool ! Thanks a lot for your quick feedback :).

**Comment by sblendorio** [comment]
Hi, I'm trying to reproduce the problem on an emulator, next week I will have my physical terminal. I ask you: what happens if you press just SPACEBAR to go next page? Does the problem persist?

**Comment by mamatdunet** [comment]
Hi,

Thank you ! It works perfectly with Space bar ! Maybe it could be useful to
indicate on a Minitel like that :

« — More — (Press spacebar) »

A nice feature for Minitel could be to use « Retour » (Previous) button and
« Suite » (Next) button to allow users to go the next page and go back to
the previous page whenever they want.

(I understand that you don’t focus on Minitel users and that this probably
a hobby for you appart from your paid job so that would be a nice to have
but the interface is already really simple and efficient 😁)

If you speak french, there is a really good documentary about Minitel
History (i don’t have the subtitles, sorry) :
https://drive.google.com/file/d/131wo7oSkq45PclpBMOeLoVthuKVCTEId/view?usp=drivesdk


Matthieu

**Comment by sblendorio** [comment]
I'm sorry but I don't speak French, but I will look at the documentary, thank you very much :)
I fixed something, I ask you to try again using SUITE, ENVOI, ... keys when "MORE" is requested.

Still arrow-keys act like double-scrolling, I'm working on it.

This project started focusing on Commodore 64, but I'm focusing now also on Minitel because I love that kind of object :) Yes, it's not my paid work, patrons like you are supporting the project, so thank you very much!

**Comment by mamatdunet** [comment]
Thanks !

Suite and Envoi buttons now have the same behaviour than Space bar :).

Congrats.

Have a nice evening ! :)

Matthieu
